export enum AppChannel {
  UnhandledException = 'unhandledException',
  CloseApp = 'closeApp',
  MinimizeApp = 'minimizeApp',
  CheckUpdate = 'checkUpdate',
  OpenDialog = 'openDialog',
  OpenDialogReturn = 'openDialogReturn',
  GetConfig = 'getConfig',
  GetUUIDV4 = 'getUUIDV4',
  UpdateConfig = 'updateConfig',
  OpenPath = 'openPath',
  OpenLog = 'openLog',
  GetPlatform = 'getPlatform',
  GetLogDir = 'getLogDir',
  GetProjects = 'getProjects',
  GetProject = 'getProject',
  RemoveProject = 'removeProject',
  MergeProjects = 'mergeProjects',
  AllProjectsAvailable = 'allProjectsAvailable',
  AllProjectsCompleted = 'allProjectsCompleted',
  ProjectChanged = 'projectChanged{id}'
}
